sudo: true

language: node_js
node_js:
  - "14.15.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - openjdk-8-jdk
      - lib32stdc++6
      - lib32z1
jdk: openjdk8

env:
  CXX=g++-4.8

install:
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update

before_script:
  - ls /usr/lib/jvm/
  - sudo rm -r /usr/lib/jvm/java-11-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - export PATH=${PATH}:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/db/bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin
  - sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java" 0
  - sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/javac" 0
  - sudo update-alternatives --set java /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java
  - sudo update-alternatives --set javac /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/javac
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  - tar -xvf android-sdk_r24.4-linux.tgz
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2

script:
  - java --version
  - cd /home/travis/build/ikaee/Faden_Mobile_Player/
  - ionic cordova build android
after_success:
  - ls /home/travis/build/ikaee/Faden_Mobile_Player/platforms/android/bin