language: node_js
node_js:
  - "14.15.1"
branches:
  only:
  - master
before_script:
- npm install -g ionic
- npm install -g cordova
- npm ci
script:
- ionic build --prod -- --base-href ./
- ionic cordova build android
after_success:
- ls ikaee/Faden_Mobile_Player/platforms/android/bin
- echo "build succeeded."