sudo: true

language: node_js
node_js:
  - "14.15.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - openjdk-8-jdk
      - lib32stdc++6
      - lib32z1

env:
  - JDK=openjdk8
  - CXX=g++-4.8
dist: trusty

install:
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update

before_script:
  - jdk_switcher use $JDK
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - export PATH=${PATH}:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/db/bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin
  - export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2:${PATH}
  - echo $JAVA_HOME
  - echo $PATH

script:
  - java -version
  - cd /home/travis/build/ikaee/Faden_Mobile_Player/
  - ionic cordova build android
after_success:
  - ls /home/travis/build/ikaee/Faden_Mobile_Player/platforms/android/bin