language: node_js
node_js:
  — "14.15.1"
branches:
  only:
  — master
before_script:
  — npm install -g ionic
  — npm ci
script:
  — ionic build --prod -- --base-href ./
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: www