platform: linux

image_resource:
  type: docker-image
  source:
    email: arshad.ali.sayed.15@gmail.com
    username: arshadalis
    password: ifafa15@docker
    repository: timbru31/java-node:8-jdk-14

inputs:
  - name: source

run:
  path: source/pipelines/tasks/scripts/build-android.sh
