platform: linux

image_resource:
  type: docker-image
  source:
    repository: beevelop/ionic:latest
    tag: latest

inputs:
  - name: source

run:
  path: source/pipelines/tasks/scripts/build-android.sh
