platform: linux

image_resource:
  type: docker-image
  source:
    email: arshad.ali.sayed.15@gmail.com
    username: arshadalis
    password: ifafa15@docker
    repository: jfloff/alpine-python
    tag: 2.7-slim

inputs:
  - name: source
  - name: folder

run:
  path: source/pipelines/tasks/scripts/upload.sh
