resources:
  - name: source-code
    type: git
    icon: github
    source:
      uri: https://github.com/ikaee/Faden_Mobile_Player.git
      branch: concourse

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: false

      - task: build-android
        file: source-code/pipelines/tasks/build-android.yaml
        input_mapping:
          source: source-code
