resources:
  - name: source-code
    type: git
    icon: github
    source:
      uri: git@github.com:ikaee/Faden_Mobile_Player.git
      branch: master

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true

      - task: build-android
        file: source-code/ci/pipelines/tasks/build-android.yaml
        input_mapping:
          source: source-code
